# 单机模式
singleServerConfig:
  password:
  timeout: 10000
  address: redis://127.0.0.1:6379
  database: 0
threads: 0
nettyThreads: 0
# 序列化
codec: !<org.redisson.codec.JsonJacksonCodec> {} # Jackson JSON 编码
#codec: !<org.redisson.codec.FstCodec> {} # FST 10倍于JDK序列化性能而且100%兼容的编码, 需要引入fst依赖包
#codec: !<org.redisson.codec.SerializationCodec> {} # JDK序列化编码
#codec: !<org.redisson.client.codec.StringCodec> {} # 纯字符串编码（无转换）
transportMode: "NIO"

# 集群模式
#clusterServersConfig:
#  idleConnectionTimeout: 10000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  failedSlaveReconnectionInterval: 3000
#  failedSlaveCheckInterval: 60000
#  password: null
#  subscriptionsPerConnection: 5
#  clientName: null
#  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 50
#  slaveConnectionMinimumIdleSize: 24
#  slaveConnectionPoolSize: 64
#  masterConnectionMinimumIdleSize: 24
#  masterConnectionPoolSize: 64
#  readMode: "SLAVE"
#  subscriptionMode: "SLAVE"
#  nodeAddresses:
#    - "redis://127.0.0.1:6380"
#    - "redis://127.0.0.1:6381"
#    - "redis://127.0.0.1:6382"
#  scanInterval: 1000
#  pingConnectionInterval: 0
#  keepAlive: false
#  tcpNoDelay: false
#threads: 6
#nettyThreads: 12
#codec: !<org.redisson.codec.JsonJacksonCodec> {}
#transportMode: "NIO"
